### ISSUE TITLE
IllegalArgumentException from DatatypeHandler for XML to XSD generation 

### ISSUE THREAD

**Issue by cyrilantony** [castor-data-binding/castor#56]
```
Caused by: java.lang.IllegalArgumentException: month 66 is out of range:  1 <= month <= 12
	at org.exolab.castor.types.DateTimeBase.setMonth(DateTimeBase.java:250)
	at org.exolab.castor.types.Date.parseDateInternal(Date.java:293)
	at org.exolab.castor.types.Date.parseDate(Date.java:240)
	at org.exolab.castor.xml.schema.util.DatatypeHandler.guessType(DatatypeHandler.java:181)
	at org.exolab.castor.xml.schema.util.XMLInstance2SchemaHandler.endElement(XMLInstance2SchemaHandler.java:220)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.exolab.castor.xml.schema.util.XMLInstance2Schema.createSchema(XMLInstance2Schema.java:143)
	at org.exolab.castor.xml.schema.util.XMLInstance2Schema.createSchema(XMLInstance2Schema.java:120)
```
Root cause : In castor/schema/src/main/java/org/exolab/castor/xml/schema/util/DatatypeHandler.java after these lines

```
try {
      Date.parseDate(value);
      return DATE_TYPE;
    } catch (ParseException px) {
    } 
```
catch the IllegalArgumentException also 
```
catch (java.lang.IllegalArgumentException px) {
}
```

**Comment by wguttmn** [comment]
Mind creating a pull request ?

**Comment by cyrilantony** [comment]
No issues. I can send a pull request. To which branch shall I send ?

**Comment by wguttmn** [comment]
Against master

**Comment by wguttmn** [comment]
Just follow the general instructions on github, and you’ll be fine.

Werner

**Comment by wguttmn** [comment]
What's the input you actually used when running into this problem ?
